### ISSUE TITLE
Missing parameters added in firmware 1.07+

### ISSUE THREAD

**Issue by aiden56** [CommanderQ/SmartThings-Edge-Drivers#2]
In particular, the locking feature: https://aeotec.freshdesk.com/support/solutions/articles/6000257235-update-illumino-dimmer-switch-v1-08 and https://aeotec.freshdesk.com/support/solutions/articles/6000257236-update-illumino-switch-v1-05.

**Comment by aiden56** [comment]
See #3

**Comment by CommanderQ** [comment]
Thank you for the update! The commit is merged and I've pushed the update to the driver channel as of 2 minutes ago. ✅
