### ISSUE TITLE
Firmware update to 47.10 breaks on/off for smart switch 6 and 7

### ISSUE THREAD

**Issue by tcsmith11** [CommanderQ/SmartThings-Edge-Drivers#8]
Adding a note here that may or may not need your attention. 
With ST hub firmware update starting 10 Apr 2023, Aeotec Smart switches using Aeotec Smart Switch 6 (Advanced Options) and Aeotec Smart Switch 7 (Advanced Options) no longer are responsive to on/off commands.  Power usage data is still visible in app so it appears to only be on/off functionality.

Reverting a switch 6 to stock drivers restores functionality.
Reverting a switch 7 to stock drivers does not restore functionality so it seems ST has broken their own driver too.

**Comment by CommanderQ** [comment]
Fixed with PR #9 thanks to guidance from Chris Cheng at Aeotec. 😄

**Comment by CommanderQ** [comment]
Thank you for filing this @tcsmith11 - I'm equally happy it's resolved now. You should see the updated driver on your hub now.
